security:
    # Configuración de los password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Proveedor de usuarios
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Configuración para el entorno de desarrollo (profiler, etc.)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall principal para la autenticación
        main:
            lazy: true
            provider: app_user_provider

            # Activar la autenticación basada en formulario
            form_login:
                login_path: login        # Ruta para mostrar el formulario de login
                check_path: login        # Ruta para procesar el formulario de login
                username_parameter: email # El parámetro que se envía desde el formulario de login (email)
                password_parameter: password # El parámetro que se envía desde el formulario de login (contraseña)
                default_target_path: /inicio # Ruta a la que redirigir después del login (ajusta según tu aplicación)

            # Configuración de logout
            logout:
                path: /logout             # Ruta para hacer logout
                # Symfony maneja el logout automáticamente

            # Habilitar las reglas de seguridad para este firewall
            security: true

    # Control de acceso para las rutas
    access_control:
        # Acceso solo para usuarios con el rol ROLE_ADMIN a la ruta /admin
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Acceso solo para usuarios con el rol ROLE_USER a la ruta /profile
        - { path: ^/profile, roles: ROLE_USER }
        # Puedes agregar otras rutas protegidas aquí según sea necesario

# Configuración de seguridad para el entorno de prueba (tests)
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4  # El valor más bajo para bcrypt en tests
                time_cost: 3  # El valor más bajo para argon en tests
                memory_cost: 10 # El valor más bajo para argon en tests
